### ISSUE TITLE
Improved Readme for starters

### ISSUE THREAD

**Issue by Pjino** [KazuCocoa/http_proxy#23]
Hi, 
I've just tried to use http_proxy and I was unable to do it, I think because my knowledge is making me do beginner mistakes. Anyway, my knowledge and Readme guidance wasn't enough to make it work, so I would like to ask  if you could clarify HOW http_proxy works with other apps.
In my case, I have two other Phoenix apps on the same server and what I've done was to start one in PORT 8080 and another in PORT 8081 and then start a third application containing http_proxy. I got a few errors because PORTs were already in use.
So, is it possible to clarify how we can make it work with 3 different apps on the same server?
Thank you!

**Comment by KazuCocoa** [comment]
Thanks for your feedback !, and sorry for my delay reply...
I will update readme for starters soon.

**Comment by KazuCocoa** [comment]
The followings are just example how to change port and add one.

----

You can handle proxy port to update `config.exs`.

The following example is changing port from 8080 to 4000 to `http://google.com` .

```elixir
use Mix.Config

config :http_proxy,
  proxies: [
             %{port: 4000,  # <= here. If you set here as 4000, the the proxy works on PORT 4000
               to:   "http://google.com"},
             %{port: 8081,
               to:   "http://yahoo.com"}
            ]
```

And if you would like to add proxy port, then you can add as the following. The following is example of adding port 4002.

```elixir
proxies: [
           %{port: 4000,
             to:   "http://google.com"},
           %{port: 4001,
             to:   "http://yahoo.com"},
           %{port: 4002,
             to:   "http://twitter.com"} # <= If you add `Map` like this one, `http_proxy` provide 3 port proxy.
          ]
```

**Comment by KazuCocoa** [comment]
Add some readme

- https://github.com/KazuCocoa/http_proxy#customize-proxy-port
- https://github.com/KazuCocoa/http_proxy#add-proxy

---

https://github.com/KazuCocoa/http_proxy/commit/58da091513aa129d91324720b46ff0dbb964e069
https://github.com/KazuCocoa/http_proxy/commit/0d538160a44e9be35b69a7dc64f85c733a45ae89
